export const SET_IS_SEARCH = "SET_IS_SEARCH";
export const SET_CITY_NAME = "SET_CITY_NAME";
export const SET_CITY_WEATHER = "SET_CITY_WEATHER";
export const SET_IS_CITY_SAVED = "SET_IS_CITY_SAVED";
export const SET_CITY_FORECAST = "SET_CITY_FORECAST";
export const SET_SAVED_CITIES = "SET_SAVED_CITIES";
export const SET_SAVED_CITIES_IDS = "SET_SAVED_CITIES_IDS";

export const ADD_CITY_ID_TO_LOCAL_STORAGE = "ADD_CITY_ID_TO_LOCAL_STORAGE";
export const REMOVE_CITY_ID_FROM_LOCAL_STORAGE =
    "REMOVE_CITY_ID_FROM_LOCAL_STORAGE";
export const GET_CITIES_IDS_FROM_LOCAL_STORAGE =
    "GET_CITIES_IDS_FROM_LOCAL_STORAGE";
export const GET_SAVED_CITIES = "GET_SAVED_CITIES";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
